create table if not exists public.branches (
  id bigint generated by default as identity primary key,
  name text not null,
  location text not null,
  branch_type text not null default 'store' check (branch_type in ('store', 'warehouse', 'massage_center')),
  phone text,
  manager_name text,
  is_active boolean not null default true
);

create table if not exists public.distributors (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  email text,
  address text,
  vendor_type text not null default 'distributor' check (vendor_type in ('distributor', 'individual', 'utility', 'landlord')),
  pending_amount numeric(12, 2) not null default 0,
  is_active boolean not null default true
);

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  email text,
  address text,
  company_name text,
  vat_number text,
  credit_limit numeric(12, 2) not null default 0,
  outstanding_balance numeric(12, 2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  full_name text,
  password_hash text not null,
  role text not null default 'admin' check (role in ('admin', 'accountant', 'auditor', 'warehouse_manager', 'store_manager', 'cashier', 'massage_manager')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_branch_access (
  user_id bigint not null references public.users(id),
  branch_id bigint not null references public.branches(id),
  access_level text not null default 'operate' check (access_level in ('view', 'operate', 'manage')),
  primary key (user_id, branch_id)
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  barcode text,
  price numeric(12, 2) not null,
  cost numeric(12, 2) not null,
  sku text,
  is_active boolean not null default true
);

create table if not exists public.inventory (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id),
  branch_id bigint not null references public.branches(id),
  stock_level integer not null default 0,
  reorder_point integer default 10,
  mfg_date text,
  expiry_date text,
  unique (product_id, branch_id)
);

create table if not exists public.stock_adjustments (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id),
  product_id bigint not null references public.products(id),
  quantity_change integer not null,
  reason text not null check (reason in ('damaged', 'expired', 'manual_count', 'theft', 'write_off', 'other')),
  note text,
  date text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.sales_records (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id),
  opening_cash numeric(12, 2) not null default 0,
  cash_taken_out numeric(12, 2) not null default 0,
  taken_by text,
  opened_at text not null,
  closed_at text,
  status text not null default 'open' check (status in ('open', 'closed')),
  notes text
);

create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id),
  record_id bigint references public.sales_records(id),
  total_amount numeric(12, 2) not null,
  payment_method text default 'cash',
  discount_amount numeric(12, 2) not null default 0,
  date text not null
);

create table if not exists public.sale_items (
  id bigint generated by default as identity primary key,
  sale_id bigint not null references public.sales(id),
  product_id bigint not null references public.products(id),
  quantity integer not null,
  price_at_sale numeric(12, 2) not null,
  discount_amount numeric(12, 2) not null default 0
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  branch_id bigint references public.branches(id),
  sales_record_id bigint references public.sales_records(id),
  type text not null check (type in ('income', 'expense')),
  category text not null,
  amount numeric(12, 2) not null,
  description text,
  date text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.purchase_orders (
  id bigint generated by default as identity primary key,
  distributor_id bigint not null references public.distributors(id),
  branch_id bigint not null references public.branches(id),
  total_amount numeric(12, 2) not null,
  paid_amount numeric(12, 2) not null default 0,
  status text default 'pending' check (status in ('pending', 'received', 'cancelled')),
  date text not null
);

create table if not exists public.purchase_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.purchase_orders(id),
  product_id bigint not null references public.products(id),
  quantity integer not null,
  cost_price numeric(12, 2) not null
);

create table if not exists public.cash_hand_entries (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id),
  type text not null check (type in ('in', 'out')),
  amount numeric(12, 2) not null,
  category text not null,
  note text,
  date text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.stock_transfers (
  id bigint generated by default as identity primary key,
  from_branch_id bigint not null references public.branches(id),
  to_branch_id bigint not null references public.branches(id),
  note text,
  date text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.stock_transfer_items (
  id bigint generated by default as identity primary key,
  transfer_id bigint not null references public.stock_transfers(id),
  product_id bigint not null references public.products(id),
  quantity integer not null
);

create table if not exists public.wholesale_sales (
  id bigint generated by default as identity primary key,
  warehouse_branch_id bigint not null references public.branches(id),
  customer_id bigint references public.customers(id),
  customer_name text,
  customer_phone text,
  total_amount numeric(12, 2) not null,
  payment_method text default 'cash',
  payment_status text not null default 'paid' check (payment_status in ('paid', 'pending', 'partial')),
  date text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.wholesale_sale_items (
  id bigint generated by default as identity primary key,
  wholesale_sale_id bigint not null references public.wholesale_sales(id),
  product_id bigint not null references public.products(id),
  quantity integer not null,
  price_at_sale numeric(12, 2) not null
);

create table if not exists public.massage_clients (
  id bigint generated by default as identity primary key,
  name text not null,
  mobile text,
  email text,
  notes text,
  visit_count integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.massage_services (
  id bigint generated by default as identity primary key,
  name text not null,
  duration_minutes integer not null,
  price numeric(12, 2) not null,
  description text,
  is_active boolean not null default true
);

create table if not exists public.massage_therapists (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  branch_id bigint not null references public.branches(id),
  is_active boolean not null default true
);

create table if not exists public.massage_sessions (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id),
  client_id bigint references public.massage_clients(id),
  client_name text,
  client_mobile text,
  therapist_id bigint references public.massage_therapists(id),
  service_id bigint references public.massage_services(id),
  booking_date text not null,
  start_time text not null,
  end_time text,
  duration_minutes integer,
  status text not null default 'scheduled' check (status in ('scheduled', 'completed', 'cancelled', 'no_show')),
  price_charged numeric(12, 2),
  payment_method text default 'cash',
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.working_schedule (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id),
  day_of_week integer not null check (day_of_week between 0 and 6),
  open_time text not null default '10:00',
  close_time text not null default '02:00',
  unique (branch_id, day_of_week)
);

create table if not exists public.break_periods (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id),
  day_of_week integer not null check (day_of_week between 0 and 6),
  break_start text not null default '13:00',
  break_end text not null default '17:00'
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id bigint references public.users(id),
  request_id text,
  ip_address text,
  table_name text not null,
  record_id bigint,
  action text not null check (action in ('insert', 'update', 'delete')),
  before_json text,
  after_json text,
  changed_data text,
  created_at timestamptz not null default now()
);

create index if not exists idx_transactions_branch_date on public.transactions(branch_id, date);
create index if not exists idx_inventory_branch_product on public.inventory(branch_id, product_id);
create index if not exists idx_sales_record_branch_status on public.sales_records(branch_id, status);
create index if not exists idx_cash_hand_branch_date on public.cash_hand_entries(branch_id, date);
create index if not exists idx_transfer_from_to_date on public.stock_transfers(from_branch_id, to_branch_id, date);
create index if not exists idx_wholesale_branch_date on public.wholesale_sales(warehouse_branch_id, date);
create index if not exists idx_massage_sessions_date on public.massage_sessions(branch_id, booking_date);
create index if not exists idx_massage_sessions_therapist on public.massage_sessions(therapist_id, booking_date);
create index if not exists idx_stock_adjustments_branch on public.stock_adjustments(branch_id, date);
create index if not exists idx_audit_log_table on public.audit_log(table_name, created_at);
